sudo: required
language: csharp
solution: ReviewProject.sln
mono: none

addons:
 snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: 2.2/stable

before_script:
 - sudo snap alias dotnet-sdk.dotnet dotnet

env:
 - BUILD: ReviewProject
 - TEST_SUITE: XUnitTestProject
 - TEST_SUITE: NUnitTestProject
 - TEST_SUITE: MSTestProjet

script:
 - "dotnet build $BUILD"
 - "dotnet test $TEST_SUITE"

