sudo: required
language: csharp
solution: ReviewProject.sln
mono: none
dotnet: 2.2

addons:
 snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/stable
  - sudo snap alias dotnet-sdk.dotnet dotnet

script:
 - dotnet restore
 - dotnet build
 - dotnet test 
