sudo: required
language: csharp
solution: ReviewProject.sln
mono: none

addons:
 snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: 2.2/stable

before_script:
 - sudo snap alias dotnet-sdk.dotnet dotnet

script:
 - dotnet test
