sudo: required
language: csharp
solution: ReviewProject.sln
mono: none

before_install:
 - gem install bundler

addons:
 snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: lts/stable

env:
 - TEST_SUITE: MSUnitTestProject
 - TEST_SUITE: NUnitTestProject
 - TEST_SUITE: XUnitTestProject

before_script:
 - sudo snap alias dotnet-sdk.dotnet dotnet

script:
 - dotnet build
 - "bundle exec rake test: $TEST_SUITE"
